/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobType = IDL.Variant({
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const JobListing = IDL.Record({
  'title' : IDL.Text,
  'jobType' : JobType,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const ProductListing = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const ContentBlock = IDL.Record({
  'value' : IDL.Text,
  'page' : IDL.Text,
  'section' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, JobType, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'createProductListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'getActiveJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getActiveProductListings' : IDL.Func(
      [],
      [IDL.Vec(ProductListing)],
      ['query'],
    ),
  'getAllContentBlocks' : IDL.Func([], [IDL.Vec(ContentBlock)], ['query']),
  'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getAllProductListings' : IDL.Func([], [IDL.Vec(ProductListing)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getContentBlock' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ContentBlock)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'seedDefaultContent' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateContentBlock' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateJobListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobType,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateProductListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const JobListing = IDL.Record({
    'title' : IDL.Text,
    'jobType' : JobType,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const ProductListing = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const ContentBlock = IDL.Record({
    'value' : IDL.Text,
    'page' : IDL.Text,
    'section' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, JobType, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createProductListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'getActiveJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getActiveProductListings' : IDL.Func(
        [],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getAllContentBlocks' : IDL.Func([], [IDL.Vec(ContentBlock)], ['query']),
    'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getAllProductListings' : IDL.Func(
        [],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getContentBlock' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ContentBlock)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'seedDefaultContent' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateContentBlock' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateJobListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobType,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateProductListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };