/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : [] | [string],
}
export interface ContentBlock {
  'value' : string,
  'page' : string,
  'section' : string,
}
export interface JobListing {
  'title' : string,
  'jobType' : JobType,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'requirements' : Array<string>,
  'location' : string,
}
export type JobType = { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export interface ProductListing {
  'features' : Array<string>,
  'tagline' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJobListing' : ActorMethod<
    [string, string, string, JobType, string, Array<string>],
    undefined
  >,
  'createProductListing' : ActorMethod<
    [string, string, string, Array<string>],
    undefined
  >,
  'getActiveJobListings' : ActorMethod<[], Array<JobListing>>,
  'getActiveProductListings' : ActorMethod<[], Array<ProductListing>>,
  'getAllContentBlocks' : ActorMethod<[], Array<ContentBlock>>,
  'getAllJobListings' : ActorMethod<[], Array<JobListing>>,
  'getAllProductListings' : ActorMethod<[], Array<ProductListing>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getContentBlock' : ActorMethod<[string, string], [] | [ContentBlock]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'seedDefaultContent' : ActorMethod<[], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'updateContentBlock' : ActorMethod<[string, string, string], undefined>,
  'updateJobListing' : ActorMethod<
    [string, string, string, JobType, string, Array<string>, boolean],
    undefined
  >,
  'updateProductListing' : ActorMethod<
    [string, string, string, Array<string>, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];