/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContentBlock {
    value: string;
    page: string;
    section: string;
}
export interface ProductListing {
    features: Array<string>;
    tagline: string;
    name: string;
    description: string;
    isActive: boolean;
}
export type Time = bigint;
export interface ContactSubmission {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone?: string;
}
export interface JobListing {
    title: string;
    jobType: JobType;
    description: string;
    isActive: boolean;
    department: string;
    requirements: Array<string>;
    location: string;
}
export enum JobType {
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createJobListing(title: string, department: string, location: string, jobType: JobType, description: string, requirements: Array<string>): Promise<void>;
    createProductListing(name: string, tagline: string, description: string, features: Array<string>): Promise<void>;
    getActiveJobListings(): Promise<Array<JobListing>>;
    getActiveProductListings(): Promise<Array<ProductListing>>;
    getAllContentBlocks(): Promise<Array<ContentBlock>>;
    getAllJobListings(): Promise<Array<JobListing>>;
    getAllProductListings(): Promise<Array<ProductListing>>;
    getCallerUserRole(): Promise<UserRole>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getContentBlock(page: string, section: string): Promise<ContentBlock | null>;
    isCallerAdmin(): Promise<boolean>;
    seedDefaultContent(): Promise<void>;
    submitContactForm(name: string, email: string, phone: string | null, message: string): Promise<void>;
    updateContentBlock(page: string, section: string, value: string): Promise<void>;
    updateJobListing(title: string, department: string, location: string, jobType: JobType, description: string, requirements: Array<string>, isActive: boolean): Promise<void>;
    updateProductListing(name: string, tagline: string, description: string, features: Array<string>, isActive: boolean): Promise<void>;
}
import type { ContactSubmission as _ContactSubmission, ContentBlock as _ContentBlock, JobListing as _JobListing, JobType as _JobType, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createJobListing(arg0: string, arg1: string, arg2: string, arg3: JobType, arg4: string, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobListing(arg0, arg1, arg2, to_candid_JobType_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobListing(arg0, arg1, arg2, to_candid_JobType_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createProductListing(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProductListing(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProductListing(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getActiveJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveJobListings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveJobListings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveProductListings(): Promise<Array<ProductListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProductListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProductListings();
            return result;
        }
    }
    async getAllContentBlocks(): Promise<Array<ContentBlock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentBlocks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentBlocks();
            return result;
        }
    }
    async getAllJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobListings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobListings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProductListings(): Promise<Array<ProductListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductListings();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentBlock(arg0: string, arg1: string): Promise<ContentBlock | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentBlock(arg0, arg1);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentBlock(arg0, arg1);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async seedDefaultContent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDefaultContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDefaultContent();
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateContentBlock(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentBlock(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentBlock(arg0, arg1, arg2);
            return result;
        }
    }
    async updateJobListing(arg0: string, arg1: string, arg2: string, arg3: JobType, arg4: string, arg5: Array<string>, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobListing(arg0, arg1, arg2, to_candid_JobType_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobListing(arg0, arg1, arg2, to_candid_JobType_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async updateProductListing(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductListing(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductListing(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_ContactSubmission_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactSubmission): ContactSubmission {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_JobListing_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobListing): JobListing {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentBlock]): ContentBlock | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
    phone: [] | [string];
}): {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone?: string;
} {
    return {
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    jobType: _JobType;
    description: string;
    isActive: boolean;
    department: string;
    requirements: Array<string>;
    location: string;
}): {
    title: string;
    jobType: JobType;
    description: string;
    isActive: boolean;
    department: string;
    requirements: Array<string>;
    location: string;
} {
    return {
        title: value.title,
        jobType: from_candid_JobType_n8(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        isActive: value.isActive,
        department: value.department,
        requirements: value.requirements,
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
}): JobType {
    return "contract" in value ? JobType.contract : "partTime" in value ? JobType.partTime : "fullTime" in value ? JobType.fullTime : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactSubmission>): Array<ContactSubmission> {
    return value.map((x)=>from_candid_ContactSubmission_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobListing>): Array<JobListing> {
    return value.map((x)=>from_candid_JobListing_n6(_uploadFile, _downloadFile, x));
}
function to_candid_JobType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} {
    return value == JobType.contract ? {
        contract: null
    } : value == JobType.partTime ? {
        partTime: null
    } : value == JobType.fullTime ? {
        fullTime: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
